export const GET_CARD_DECKS = "GET_CARD_DECKS";
export const SELECT_DECK  = "SELECT_DECK";
export const UPDATE_STUDY_RESULT = "UPDATE_STUDY_RESULT";
export const UPDATE_SLIDING_STATUS = "UPDATE_SLIDING_STATUS";